### ISSUE TITLE
SkullOwner Tag

### ISSUE THREAD

**Issue by mtuska** [Dablakbandit/DabCore#1]
The DabCore ItemUtils simply compare all tags together and return false if not all tags are equal. While this is usually fine, with custom Skulls, this is not possible with their unique "Id" tag inside the "SkullOwner" tag. I already made a custom DabCore build with this fix.

Also, I'd like to ask about the GRandExchange, as using the mysql seems to halt execution of the entire server for atleast 5 minutes. If I could, I'd like to get a personal copy/purchase of the GrandExchange. I have no intent of releasing any custom versions/code of the GrandExchange, I simply want to be able to make my own changes/fixes.

Thanks, please get back to me when you have a chance.

**Comment by Dablakbandit** [comment]
Then create a pull request for the custom skull fix?

As for the mysql, is it running on the same system or remote? When I load up a server it works find and starts instantly, could you provide logs?

**Comment by mtuska** [comment]
For my SkullOwner fix, it simply skips the SkullOwner tag, so technically people couldn't buy/sell a specific player's head. If that's fine with you I can create the pull request.

-Snipped the GrandExchange bit in favor of Spigot, as it is more fitting over there.

**Comment by mtuska** [comment]
Here's the pr
https://github.com/Dablakbandit/DabCore/pull/2
